//go:build !noasm && amd64
// AUTO-GENERATED BY GOCC -- DO NOT EDIT

package roaring

import "unsafe"

//go:noescape,nosplit
func _find16(input unsafe.Pointer, target uint16, result unsafe.Pointer, size uint64)
